### ISSUE TITLE
Closing multiple issues, throws error

### ISSUE THREAD

**Issue by youzi** [node-gh/gh#395] opened 2015-06-26 11:48 UTC
eg.
`gh is -n 55 -n 51 -n 37 -C`
produces the following:

```
Closing issue #55 on <repo-goes-here>
Closing issue #51 on <repo-goes-here>
Closing issue #37 on <repo-goes-here>
https://github.com/<repo-goes-here>/issues/51
/Users/youzi/npm/lib/node_modules/gh/lib/cmds/issue.js:133
                afterHooksCallback();
                ^
TypeError: undefined is not a function
    at /Users/youzi/npm/lib/node_modules/gh/lib/cmds/issue.js:133:17
    at /Users/youzi/npm/lib/node_modules/gh/node_modules/github/api/v3.0.0/issues.js:278:17
    at callCallback (/Users/youzi/npm/lib/node_modules/gh/node_modules/github/index.js:743:17)
    at IncomingMessage.<anonymous> (/Users/youzi/npm/lib/node_modules/gh/node_modules/github/index.js:796:25)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by henvic** [comment] 2015-06-26 17:07
Duplicate of https://github.com/node-gh/gh/issues/367

Thanks for reporting.

**Closed** 2017-11-18 00:57 UTC
